Archive (2021-06-01 / or older) 2

diff --git a/sudo b/sudo
--- a/sudo
+++ b/sudo
@@ -1,6 +1,5 @@
 #!/bin/sh
-
-set -u
+set -eu
 
 export SUDO_USER=${USER:-$(id -un)} SUDO_UID=${EUID:-$(id -u)} SUDO_GID=${GROUPS:-$(id -g)}
 export SUDO_COMMAND=$@
@@ -13,24 +12,71 @@ _sudo_shell=
 _sudo_background=
 _sudo_bell=
 _sudo_chdir=
-
 _sudo_to_exit=
 _sudo_to_usage=
 
+_sudo_arg_i=
+_sudo_arg_val=
+
+
 err() {
 	printf '%s\n' "$1"
-	[ -n "$2" ] && [ "$2" != 0 ] && _sudo_to_exit="${2:-1}"
+	[ "${2:-0}" != 0 ] && _sudo_to_exit="${2:-1}" 
 	# the reason it to print alot error messages
 	# and then exit with wast err_code (not 0)
 }
 
 while [ "$#" -ne 0 ]; do
+
+	  # -C, --close-from=num
+	  # -D, --chdir=directory
+	      # --preserve-env=list
+	  # -g, --group=group
+	  # -h, --host=host
+	  # -p, --prompt=prompt
+	  # -R, --chroot=directory
+	  # -T, --command-timeout=timeout
+	  # -U, --other-user=user
+	  # -u, --user=user
+	_sudo_arg_i=''
+
 	case $1 in
+		*=*) export "$1";;
 		--) shift; break;;
-		-A) _sudo_askpass=$SUDO_ASKPASS; [ -z "$_sudo_askpass" ] && err "no askpass program specified, try setting SUDO_ASKPASS" 1;; # used $SUDO_ASKPASS from env
-		# -B|--bell) _sudo_bell='\a';;
+		--bell) _sudo_arg_i='-b';;
+		
+		*)_sudo_arg_i=$1; ##TODO: :: RM THIS LINE ASAP :: :TODO
+	esac
+
+	case $_sudo_arg_i in
+		
+		-*)
+			_sudo_arg_i=${1%%[CDghpRTUu]*} # get valuae of options that reguire argument
+			_sudo_arg_val=${1#"$i"}
+		;;
+#		*) err "Error parsing '$1', _sudo_arg_i='$_sudo_arg_i'";;
+	esac
+
+
+	# if [ "$_sudo_arg_val" = '' ] || cate
+
+
+
+	case $_sudo_arg_i in
+
+		-A) _sudo_askpass=$SUDO_ASKPASS; [ -z "$_sudo_askpass" ] && err "no askpass program specified, try setting SUDO_ASKPASS" 1;;
+		# used $SUDO_ASKPASS from env? never tested?
+
+		-B|--bell) _sudo_bell='\a';; # todo : add to begining in prompt
+		# it assumes that password aways will be neded, exept for root,
+		#  password is not neede for Android su, however there is no easy way to detect if pass will be neede
+
 		# -C, --close-from=num   # todo: wut
-		-D*)_sudo_chdir="${1#-D}";; --chdir=*) _sudo_chdir="${1#--chdir}";;   # 9/10 - by most default sudoers config  -D is not alowed for user? # todo further check if true
+
+		-D*)_sudo_chdir="${1#-D}";;
+		--chdir=*) _sudo_chdir="${1#--chdir}";;
+		# 9/10 - by most default sudoers config  -D is not alowed for user? # todo further check if true 
+
 		# -E|--preserve-env) ;; # MUST HAVE, now is like it is passed -E
 		
 		
@@ -43,12 +89,15 @@ while [ "$#" -ne 0 ]; do
 		-i) _sudo_login=-l;;
 		-s) _sudo_shell=1;;
 		-b) _sudo_background='&';;
+
 		-h|--help) _sudo_to_usage=long-message;;
+
 		-*) echo 1>&2 "sudo: not supported option option: $1"; _sudo_to_exit=1;;
 		*=*) export "$1";;
 		*) break;;
 	esac
 	shift
+#	arg "$@"
 done
 
 # case $_sudo_to_usage in
@@ -79,11 +128,9 @@ printf "$_sudo_bell" >/dev/tty
 	# cd "$_sudo_chdir"  # shoud not  WHEN [ -n "$_sudo_login$_sudo_shell" ] && [ "$#" -eq 0 ]
 
 	# expected "su" to read passwrod from stdin by default,  not tested on all platforms
-	# bug: 'Password:' prompt will be outputed to STDERR not /dev/tty, micro will not prompt
-	# bug: I/O /dev/tty in invoked command will fail ""
 
 	# ${_sudo_login:+"$_sudo_login"} -> dont risk IFS to include '-l'
-if [ "$SUDO_UID" -eq 0 ] && [ "$_sudo_user" = root ] || [ "$SUDO_USER" = "$_sudo_user" ]  &&false; then
+if [ "$SUDO_UID" -eq 0 ] && [ "$_sudo_user" = root ]; then
 	eval 'exec "$@"'" $_sudo_background"
 	# todo: checking for  _sudo_login/_sudo_shell
 
@@ -95,7 +142,7 @@ elif [ "$_sudo_stdin" -eq 1 ]; then
 	fi
 else
 	if [ -n "$_sudo_login" ]; then
-		err '! _sudo_login withot stdin' 3
+		err \!" _sudo_login withot stdin" 3
 		# todo:$_sudo_background ?
 		# exec su ${_sudo_login:+"$_sudo_login"} -c 'cd "$0" && exec <&3 "${SHELL:-/bin/sh}"' -- "$_sudo_user" "$_sudo_chdir" 3<&0 </dev/tty
 	elif [ -n "$_sudo_shell" ]; then
@@ -104,10 +151,10 @@ else
 	else
 		# exec su -c 'cd "$0" && exec 0<&9 2>&9 "$@"'" $_sudo_background" -- "$_sudo_user" "$_sudo_chdir" "$@" 9<&0 0</dev/tty 9>&2 2>/dev/tty
 # TODO $_sudo_chdir
+# TODO $_sudo_askpass
 		# use su-cmd-shell in case of error message
 		# exec su -c '"$@"'" $_sudo_background" -- "$_sudo_user" "su-cmd-shell" "$@"
-		exec su -c '"$@" 0<&9 1>&8 2>&7'" ${_sudo_background:+&}" -- "$_sudo_user" "su-cmd-shell" "$@" 9<&0 8>&1 7>&2  0</dev/tty 1>/dev/tty 2>/dev/tty
-		echo old is exec su -c '"$@" 0<&9 1>&8 2>&9'" ${_sudo_background:+&}" -- "$_sudo_user" "su-cmd-shell" "$@" 9<&0 0</dev/tty  9>&1 8>&1 9>&2  1>/dev/tty 2>/dev/tty
+		exec su -c 'exec "$@"  0<&9 1>&8 2>&7  9>&- 8>&- 7>&-'"  $_sudo_background ; exit # " -- "$_sudo_user" "su-cmd-shell" "$@"  9<&0 8>&1 7>&2  0</dev/tty 1>/dev/tty 2>/dev/tty 
 	fi
 	# exec su -c 'if [ "$SHELL" = "$0" ]; then cd "$1";shift;else cd "$0"; fi ; exec <&3 "$@"' "$_sudo_user" -- "$_sudo_chdir" "$@" 3<&0 </dev/tty
 fi
