improve arguments a bit

diff --git a/sudo b/sudo
--- a/sudo
+++ b/sudo
@@ -1,59 +1,87 @@
 #!/bin/sh
 set -feu
 
-export SUDO_COMMAND=$@ SUDO_USER=${USER:-$(id -un)} SUDO_UID=${EUID:-$(id -u)} SUDO_GID=${GROUPS:-$(id -g)}
+export SUDO_COMMAND="$*" SUDO_USER SUDO_UID SUDO_GID
+SUDO_USER=${USER:-$(id -un)}
+SUDO_UID=${EUID:-$(id -u)}
+SUDO_GID=${GROUPS:-$(id -g)}
 
 err() {
 	printf '%s\n' "${0##*/}: $1" >&2
 	exit "${2:-1}" 
 }
 
+_sudo_arg_val() {
+	[ "$_sudo_arg_val" != '' ] || err "empty value for $1 not allowed"
+}
+
 # safe check if var is NOT exported
 vars() {
 	for i; do
-		eval "if ( : \"\${${i}:?}\"; ); then return \$? ; else ${i}=''; fi "
-	done 1>/dev/null 2>/dev/null
+		        # (set -u) is needed!
+		eval "if ( : \"\${${i}}\"; ); then echo NO $i return 1 ; else ${i}=''; fi "
+	done 2>/dev/null 2>/dev/null
 }
+
+
+
+# vars a a || exit $?
+# exit 0
+## some GENERATED USING: sudo -h  | sed -nEe '/^  -[^-]+/ { s/.*--([^ =]+).*/_sudo_\1 \\/; s/-/_/; p; }'
 vars \
 	_sudo_askpass \
-	\
-	_sudo_user \
-	_sudo_stdin \
-	\
-	_sudo_login \
-	_sudo_shell \
 	_sudo_background \
 	_sudo_bell \
+	_sudo_close_from \
 	_sudo_chdir \
-	_sudo_to_exit \
-	_sudo_to_usage \
+	_sudo_preserve_env \
+	_sudo_edit \
+	_sudo_group \
+	_sudo_set_home \
+	_sudo_help \
+	_sudo_host \
+	_sudo_login \
+	_sudo_remove_timestamp \
+	_sudo_reset_timestamp \
+	_sudo_list \
+	_sudo_non_interactive \
+	_sudo_preserve_groups \
+	_sudo_prompt \
+	_sudo_chroot \
+	_sudo_stdin \
+	_sudo_shell \
+	_sudo_command_timeout \
+	_sudo_other_user \
+	_sudo_user \
+	_sudo_version \
+	_sudo_validate \
+	\
 	\
 	_sudo_opts \
 	_sudo_opts_ \
 	_sudo_arg_key \
 	_sudo_arg_val \
 	\
-	_sudo_env_vars \
-	|| exit
-
+|| exit
 
 _sudo_user=root
-_sudo_stdin=0
 
 
 while [ "$#" -ne 0 ]; do
 #  would it be better to iterate using $(substr "$1" "$i" 1) through short args args
 	# _sudo_opts=$1 # should not be needed, just in case
+	_sudo_arg_key=''
 	unset _sudo_opts_
-	unset _sudo_arg_key
 	unset _sudo_arg_val
 
 	# first convent short args to long args:
 
 	case $1 in
 		--) shift; break;;
+		[!-]*=*) _sudo_env_vars=1; export "$1"; continue;;
+		[!-]*) break;; # end of args?
+
 		-[CDghpRTUu]*|-[!-]*[CDghpRTUu]*)
-		# if is not long arg, get only current short arg and sepanate its vanue
 			# get valuae of options that reguire argument
 
 			_sudo_opts_=${1%%[CDghpRTUu]*}
@@ -70,21 +98,21 @@ while [ "$#" -ne 0 ]; do
 			|| err "error parsing arguments in -- '${1:-}'" 2
 
 
-			_sudo_opts=$_sudo_opts${_sudo_opts#-}
+			_sudo_opts=${_sudo_opts_#-}$_sudo_opts
 			# _sudo_arg_key=$_sudo_arg_key$_sudo_arg_key
 			[ "$_sudo_arg_val" != '' ] || {
 				if [ 2 -le $# ]; then
 					_sudo_arg_val=$2 && shift
+				elif [ "$_sudo_arg_key" = h ] && case ${2:-} in -*) false; esac; then # what will happen when -h - or other case
+					_sudo_opts=h$_sudo_opts
+					_sudo_arg_key=''
 				else
-					[ "$_sudo_arg_key" = -h ] && _sudo_opts=h$_sudo_opts
-				fi || err "option requires an argument -- '$1'"
+					 err "option requires an argument -- '$1'"
+				fi
 			}
 		;;
 		-[!-]*) _sudo_opts=${1#-}$_sudo_opts;;
 
-		[!-]*=*) _sudo_env_vars=@; export "$1"; continue;;
-
-		[!-]*) break;; # end of args?
 
 		###### GENERATED USING: sudo -h | sed -nEe 's/^  (-[^-]+), (--[^ =]+) .+/\2) _sudo_opts=\1;;/p'
 		--askpass)          _sudo_opts=A$_sudo_opts;;
@@ -105,67 +133,78 @@ while [ "$#" -ne 0 ]; do
 		--version)          _sudo_opts=V$_sudo_opts;;
 		--validate)         _sudo_opts=v$_sudo_opts;;
 		--*) # need to parse options with arg separately
-			case ${1#--} in
-				preserve-env|preserve-env=?*) err "err, unimplemented option -- '${1%%=*}'";; # we do not have a short option for this one
-				###### GENERATED USING: sudo -h  | sed -nEe 's/^  (-[^-]+), --([^ =]*)=[^ =]+ .+/\2|\2=?*) _sudo_arg_key=\1;;/p'
-				close-from|close-from=?*)           _sudo_arg_key=C;;
-				chdir|chdir=?*)                     _sudo_arg_key=D;;
-				group|group=?*)                     _sudo_arg_key=g;;
-				host|host=?*)                       _sudo_arg_key=h;;
-				prompt|prompt=?*)                   _sudo_arg_key=p;;
-				chroot|chroot=?*)                   _sudo_arg_key=R;;
-				command-timeout|command-timeout=?*) _sudo_arg_key=T;;
-				other-user|other-user=?*)           _sudo_arg_key=U;;
-				user|user=?*)                       _sudo_arg_key=u;;
+			case ${1#"--"} in
+				# todo what option what should do when is empty (--user='')
+				preserve-env=*) err "err, unimplemented option -- '${1%%=*}'" ; sudo_arg_val=;; # ony value when has '=' 
+				###### GENERATED USING: sudo -h  | sed -nEe 's/^  (-[^-]+), --([^ =]*)=[^ =]+ .+/\2|\2=*) _sudo_arg_key=\1;;/p'
+				close-from|close-from=*)           _sudo_arg_key=C;;
+				chdir|chdir=*)                     _sudo_arg_key=D;;
+				group|group=*)                     _sudo_arg_key=g;;
+				host|host=*)                       _sudo_arg_key=h;;
+				prompt|prompt=*)                   _sudo_arg_key=p;;
+				chroot|chroot=*)                   _sudo_arg_key=R;;
+				command-timeout|command-timeout=*) _sudo_arg_key=T;;
+				other-user|other-user=*)           _sudo_arg_key=U;;
+				user|user=*)                       _sudo_arg_key=u;;
 
 				*) err "unrecognized option '$1'";;
 			esac
-			case $1 in
+			( : "$_sudo_arg_val" ) 2>/dev/null || case $1 in
 				*=*) _sudo_arg_val=${1#*=};;
 				*)
 					[ 2 -le $# ] && _sudo_arg_val=$2 && shift \
 					|| err "option '$1' requires an argument'"
 				;;
 			esac
+
+			[ "$_sudo_arg_val" != '' ] \
+			|| case $_sudo_arg_key in [ug]) # options that requires values
+				err "Error empty value for $_sudo_arg_key"
+			esac
 		;;
 
 		*) err "Error parsing '$1', args($#) left: $*" 111;;
 	esac
 	
-(set -x +ue # easy way to deug
-	__1=$1
-	_sudo_opts=$_sudo_opts
-	_sudo_opts_=$_sudo_opts_
-	_sudo_arg_val=$_sudo_arg_val
-	_sudo_arg_key=$_sudo_arg_key
-)||:
+#(
+#exit 0 # now no need to debug
+#set -x # easy way to deug
+#	__1=$1
+#	_sudo_opts=$_sudo_opts
+#	_sudo_opts_=$_sudo_opts_
+#	_sudo_arg_val=$_sudo_arg_val
+#	_sudo_arg_key=$_sudo_arg_key
+#)||: # debug log
 
 
-
-	case ${_sudo_arg_key:-} in
-		'') ;;
-		# @ close-from|close-from=?*)           _sudo_arg_key=C;;
-		# -C, --close-from=num   # todo: wut
-		# @ chdir|chdir=?*)                     _sudo_arg_key=D;;
-		D) _sudo_chdir="$_sudo_arg_val";;
-		# 9/10 - by most default sudoers config  -D is not alowed for user? # todo further check if; true 
-		# @ group|group=?*)                     _sudo_arg_key=g;;
-		# @ host|host=?*)                       _sudo_arg_key=h;;
-		# h) _sudo_to_usage=long-message
-		# @ prompt|prompt=?*)                   _sudo_arg_key=p;;
-		# @ chroot|chroot=?*)                   _sudo_arg_key=R;;
-		R) _sudo_unimplemented=1;; #_sudo_chroot=$_sudo_arg_val
-		#  "you are not permitted to use the -R option with ..." ah sudo rules, todo some day
-		# @ command-timeout|command-timeout=?*) _sudo_arg_key=T;;
-		# @ other-user|other-user=?*)           _sudo_arg_key=U;;
-		# @ user|user=?*)                       _sudo_arg_key=u;;
-		u) _sudo_user=$_sudo_arg_val;; # PLS work from the first time, pretty pls
-		*) err "err, unimplemented option -- '$_sudo_arg_key'";;
-	esac
+	# todo  complain abut empty optiont
+	if [ "$_sudo_arg_key" != '' ]; then
+		# case $_sudo_arg_key in [ug]) err
+		case $_sudo_arg_key in
+			'') ;;
+			# @ close-from|close-from=?*)           _sudo_arg_key=C;;
+			# -C, --close-from=num   # todo: wut
+			# @ chdir|chdir=?*)                     _sudo_arg_key=D;;
+			D) _sudo_chdir="$_sudo_arg_val";;
+			# 9/10 - by most default sudoers config  -D is not alowed for user? # todo further check if; true 
+			# @ group|group=?*)                     _sudo_arg_key=g;;
+			g) _sudo_group="$_sudo_arg_val"; _sudo_arg_val group;;
+			# @ host|host=?*)                       _sudo_arg_key=h;;
+			# @ prompt|prompt=?*)                   _sudo_arg_key=p;;
+			# @ chroot|chroot=?*)                   _sudo_arg_key=R;;
+			R) _sudo_unimplemented=1;; #_sudo_chroot=$_sudo_arg_val
+			#  "you are not permitted to use the -R option with ..." ah sudo rules, todo some day
+			# @ command-timeout|command-timeout=?*) _sudo_arg_key=T;;
+			# @ other-user|other-user=?*)           _sudo_arg_key=U;;
+			# @ user|user=?*)                       _sudo_arg_key=u;;
+			u) _sudo_user=$_sudo_arg_val; _sudo_arg_val name;; # PLS work from the first time, pretty pls
+			*) err "err, unimplemented option -- '$_sudo_arg_key'";;
+		esac
+	fi
 
 
 	shift
-	# arg "$@" # debug log todo: rm me
+	# arg "$@" # debug log
 done
 
 
@@ -177,7 +216,21 @@ done
 
 
 if [ "$_sudo_opts" != '' ]; then
+	# TODO: parse invalid options
 
+
+
+	: TODO : <<- TODO
+		the -A and -S options may not be used together
+		Only one of the -e, -h, -i, -K, -l, -s, -v or -V options may be specified
+		the -U option may only be used with the -l option
+		the argument to -C must be a number greater than or equal to 3
+		you are not permitted to use the -D option with
+		you may not specify both the -i and -E options
+		
+	TODO
+
+	
 	# @ --askpass)          _sudo_opts=A;;
 	case ${_sudo_opts:?} in *A*)
 		[ "${SUDO_ASKPASS:-}" != '' ] || err "no askpass program specified, try setting SUDO_ASKPASS"
@@ -198,17 +251,17 @@ if [ "$_sudo_opts" != '' ]; then
 
 	# @ --edit)             _sudo_opts=e;;
 		# sudo will complain 'you may not specify environment variables in edit mode', but this script will not
-		# also will create tmp file, hire we execute the EDITOR directly with the user on the file
-	case $_sudo_opts in *e*)
+		# also original will create tmp file, hire we execute the EDITOR directly with the user on the file
+	case $_sudo_opts in *e*) # _sudo_edit=1
 		set -- "${EDITOR:-vi}" "$@" # only outside the loop use 'set --' for -e option
 	esac
 	
 
 	# @ --set-home)         _sudo_opts=H;;
-	case $_sudo_opts in *H*) err "err, unimplemented option -- 'H'";esac
+	case $_sudo_opts in *H*) err "err, unimplemented option -- 'H'";esac # todo combined with -E
 
 	# @ --help)             _sudo_opts=h;;
-	case $_sudo_opts in *h*) err "err, unimplemented option -- 'h'";esac # todo: next
+	case $_sudo_opts in *h*) _sudo_help=0; esac # todo: only help should be specified ? or (sudo -k -h) only???
 
 	# @ --login)            _sudo_opts=i;;
 	case $_sudo_opts in *i*) _sudo_login=1; esac
@@ -217,19 +270,19 @@ if [ "$_sudo_opts" != '' ]; then
 	case $_sudo_opts in *K*) _sudo_remove_timestamp=1; esac
 
 	# @ --reset-timestamp)  _sudo_opts=k;;
-	#SKIPED
+	: # done, nothing to do for this option
 
 	# @ --list)             _sudo_opts=l;;
 	case $_sudo_opts in *l*) err "err, unimplemented option -- 'l'";esac
 	# @ --non-interactive)  _sudo_opts=n;;
-	case $_sudo_opts in *i*) err "err, unimplemented option -- 'i'";esac
-	# @ --preserve-groups)  _sudo_opts=P;;
+	case $_sudo_opts in *n*) _sudo_non_interactive=1;esac
+	# @ --preserve-groups)
 	case $_sudo_opts in *P*) err "err, unimplemented option -- 'p'";esac
 	# @ --stdin)            _sudo_opts=S;;
 	case $_sudo_opts in *S*) _sudo_stdin=1; esac
 	# @ --shell)            _sudo_opts=s;;
 	case $_sudo_opts in *s*)
-		[ "$_sudo_login" = 1 ]] && err 'you may not specify both the -i and -s options'
+		[ "$_sudo_login" = 1 ] && err 'you may not specify both the -i and -s options'
 		_sudo_shell=1
 	esac
 	# @ --version)          _sudo_opts=V;;
@@ -238,20 +291,49 @@ if [ "$_sudo_opts" != '' ]; then
 	case $_sudo_opts in *v*) err "err, unimplemented option -- 'v'";esac
 fi
 
-
-
-
-
-
-# TODO CONTINUE HIRE ${dstndstndstndstndstn?}
-# exit 123
-
-# case $_sudo_to_usage in
-#	help) TODO help message;;
-#	usage) TODO 2-5 lies usage;;
-# esac
-
-[ -n "$_sudo_to_exit" ] && exit "$_sudo_to_exit"
+#echo  $_sudo_help
+[ "$_sudo_help" = '' ] || {
+	printf %s\\n \
+		"sudo - execute a command as another user"\
+		""\
+		"usage: sudo -h | -K | -k | -V"\
+		"usage: sudo -v [-ABknS] [-g group] [-h host] [-p prompt] [-u user]"\
+		"usage: sudo -l [-ABknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]"\
+		"usage: sudo [-ABbEHknPS] [-C num] [-D directory] [-g group] [-h host] [-p prompt] [-R directory] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]"\
+		"usage: sudo -e [-ABknS] [-C num] [-D directory] [-g group] [-h host] [-p prompt] [-R directory] [-T timeout] [-u user] file ..."\
+		""\
+		"Options:"\
+		"#   -A, --askpass                 use a helper program for password prompting"\
+		"    -b, --background              run command in the background"\
+		"    -B, --bell                    ring bell when prompting"\
+		"#   -C, --close-from=num          close all file descriptors >= num"\
+		"#   -D, --chdir=directory         change the working directory before running command"\
+		"#?  -E, --preserve-env            preserve user environment when running command"\
+		"        --preserve-env=list       preserve specific environment variables"\
+		"#   -e, --edit                    edit files instead of running a command"\
+		"#   -g, --group=group             run command as the specified group name or ID"\
+		"#   -H, --set-home                set HOME variable to target user's home dir"\
+		"    -h, --help                    display help message and exit"\
+		"    -h, --host=host               run command on host (if supported by plugin)"\
+		"    -i, --login                   run login shell as the target user; a command may also be specified"\
+		"    -K, --remove-timestamp        remove timestamp file completely"\
+		"#   -k, --reset-timestamp         invalidate timestamp file"\
+		"#   -l, --list                    list user's privileges or check a specific command; use twice for longer format"\
+		"#   -n, --non-interactive         non-interactive mode, no prompts are used"\
+		"#   -P, --preserve-groups         preserve group vector instead of setting to target's"\
+		"#   -p, --prompt=prompt           use the specified password prompt"\
+		"#   -R, --chroot=directory        change the root directory before running command"\
+		"    -S, --stdin                   read password from standard input"\
+		"    -s, --shell                   run shell as the target user; a command may also be specified"\
+		"#   -T, --command-timeout=timeout terminate command after the specified time limit"\
+		"#   -U, --other-user=user         in list mode, display privileges for user"\
+		"    -u, --user=user               run command (or edit file) as specified user name or ID"\
+		"    -V, --version                 display version information and exit"\
+		"#   -v, --validate                update user's timestamp without running a command"\
+		"    --                            stop processing command line arguments"\
+	;
+	exit "$_sudo_help"
+}
 
 [ -n "$_sudo_shell" ] && [ -n "$_sudo_login" ] && {
 	echo >&2 'sudo: you may not specify both the -i and -s options'
@@ -260,29 +342,68 @@ fi
 }
 
 [ "$#" -eq 0 ] && [ "$_sudo_login$_sudo_shell" = '' ] && {
-	echo TODO usage help message
+	echo TODO usage help message-
 	exit 1
 }
 
-printf "$_sudo_bell" >/dev/tty
-# [ -t 2 ] || printf 'Password: ' >/dev/tty # todo: better way
+# is tty used in real sudo for the bell
+printf %b "${_sudo_bell:+BELL\\n}" >/dev/tty 
 
-: ${_sudo_chdir:=${PWD:-$(pwd)}}
-: ${_sudo_user:=root}
-# print 'Password: ' to tty in case /dev/stderr is redirected
+[ "$_sudo_chdir" != '' ] || _sudo_chdir=${PWD:-$(pwd)}
 
 	# cd "$_sudo_chdir"  # shoud not  WHEN [ -n "$_sudo_login$_sudo_shell" ] && [ "$#" -eq 0 ]
 
 	# expected "su" to read passwrod from stdin by default,  not tested on all platforms
-	# bug: 'Password:' prompt will be outputed to STDERR not /dev/tty, micro will not prompt
-	# bug: I/O /dev/tty in invoked command will fail ""
+	# bug: I/O /dev/tty in invoked command will fail "" . Should it test if /dev/tty is r/w-able?
 
-	# ${_sudo_login:+"$_sudo_login"} -> dont risk IFS to include '-l'
-if [ "$SUDO_UID" -eq 0 ] && [ "$_sudo_user" = root ]; then
+
+if [ "$_sudo_user" != root ]; then
+	case $_sudo_user in *[!0-9]*) true;; *) false; esac \
+	&& _sudo_tmp=$(id -un -- "$_sudo_user" 2>&-) \
+	|| err "unknown user: $_sudo_user"
+
+	[ "$_sudo_tmp" = "$_sudo_user" ] \
+	|| err \
+		"Error uanexpected ousput from id,`:
+		` expected: _sudo_user='$_sudo_user',`:
+		` got: '$_sudo_tmp'"\
+	;
+fi
+
+if [ "$_sudo_group" != '' ]; then
+	command -v __getent >/dev/null \
+	&& _sudo_tmp=$(getent -- group "$_sudo_group") \
+	|| _sudo_tmp=$(cut -d : -f 1 "${PREFIX:-}"/etc/group | tr $'\n' :)
+
+	case ":$_sudo_tmp" in
+		*:"$_sudo_group":*)
+			case " $(id -Gn -- "$_sudo_user") " in
+				*" $_sudo_group "*);;  # all good, user is in the group
+				*)
+					printf %s \
+						"Sorry, user $SUDO_USER" \
+						" is not allowed to execute '$1'" \
+						" as $_sudo_user:$_sudo_group" \
+						" on ${NAME:-$(hostname)}."
+						# in $NAME hostname for all distros that use it, todo check?
+					echo
+					exit 1
+				;;
+			esac
+		;;
+		:*:) err "unknown group: $_sudo_group";;
+		*) err "Error invalid output for groups: '$_sudo_tmp'";;
+	esac
+fi
+
+
+
+if [ "$SUDO_UID" -eq 0 ] && [ "$_sudo_user" = "$SUDO" ]; then
 	eval 'exec "$@"'" $_sudo_background"
 	# todo: checking for  _sudo_login/_sudo_shell
-
-elif [ "$_sudo_stdin" -eq 1 ]; then
+elif [ "$_sudo_non_interactive" = 1 ]; then
+	err 'a password is required'
+elif [ "$_sudo_stdin" = 1 ]; then
 	if [ -n "$_sudo_login$_sudo_shell" ]; then
 		exec su ${_sudo_login:+"$_sudo_login"} -- "$_sudo_user"
 	else
@@ -306,3 +427,6 @@ else
 	fi
 	# exec su -c 'if [ "$SHELL" = "$0" ]; then cd "$1";shift;else cd "$0" && fi ; exec <&3 "$@"' "$_sudo_user" -- "$_sudo_chdir" "$@" 3<&0 </dev/tty
 fi
+
+
+# print 'Password: ' to tty in case /dev/stderr is redirected
